### PR TITLE
Rich comparison and magic methods for ComparableVersion

### PR DESCRIPTION
**Pull request by CermakM**
- implement magic methods to represent ComparableVersion
- implement some of rich comparison methods

- propose solution to handle NoneType comparison

Signed-off-by: Marek Cermak <prace.mcermak@gmail.com>

modified:   f8a_version_comparator/comparable_version.py

### CODE REVIEW

**Comment by CermakM** [comment]
The PR targets #12 and #13

**Comment by tisnik** [comment]
FYI: the CI job is failing: https://ci.centos.org/job/devtools-fabric8-analytics-version-comparator-fabric8-analytics/5/console

**Comment by tisnik** [comment]
I'm still not sure if it is a good idea to use unsupported Python version :) @msrb WDYT? We know it was a bit hard to setup it for NVD toolkit...

**Comment by CermakM** [comment]
Thanks for the info @tisnik .. I haven't set up requirements.txt yet, that's why it failed.

About the unsupported Python version ... Did I use any features that are not supported in our Python 3.4.x version? If you meant the type hints, shouldn't they be supported?

**Comment by tisnik** [comment]
@CermakM FYI the CI job: https://ci.centos.org/job/devtools-fabric8-analytics-version-comparator-fabric8-analytics/

**Comment by tisnik** [comment]
It looks good, thank you @CermakM

**Pull request merged**
